### ISSUE TITLE
Heuristic Function

### ISSUE THREAD

**Issue by BrendanAnnable** [MaartenBaert/2048-ai-emscripten#1]
I have been studying your code and wish to make a bit more sense of your heuristic function.

Looking at the code [here](https://github.com/MaartenBaert/2048-ai-emscripten/blob/master/Minimax.cpp) I can see you're using some kind of centerofmass value function? Along with points for opencells which makes sense.

Would you be able to explain what it is doing and why the bitshifts and things?

Thanks.

**Comment by MaartenBaert** [comment]
Yes, I give score based on the number of free cells and the position of the center of mass. The parameters change the weight of the tiles:

```
weight = value * CENTEROFMASS1 + value^2 * CENTEROFMASS2 + value^3 * CENTEROFMASS3 + value^4 * CENTEROFMASS4
```

I use integers because it's slightly faster than floating point, but since I can't represent fractional numbers, I just make the parameters 1024 times larger and I right-shift by 10 at the end (it's essentially fixed point instead of floating point).

I've actually done a full rewrite that I hadn't pushed yet, the new version is a lot faster and I think it's also easier to read. I've pushed it now (I didn't actually test it with emscripten yet, so that may not work just yet).
